[templates.dmspywalfox]
input_path = 'SHELL_DIR/matugen/templates/pywalfox-colors.json'
output_path = 'CACHE_DIR/wal/dank-pywalfox.json'
post_hook = 'sh -c "command -v pywalfox && test -f ~/.cache/wal/colors.json && pywalfox update"'
